CREATE DATABASE MessagingAPI;

USE MessagingAPI;

CREATE TABLE IF NOT EXISTS UsersAuth (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(512) NOT NULL UNIQUE,
    password VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS Messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    msgFrom INT NOT NULL,
    msgTo INT NOT NULL,
    message TEXT NOT NULL,
    msgTime DATETIME NOT NULL
);
